### PR TITLE
removed redundant declarations

### PR DESCRIPTION
**Pull request by smart--petea**
I removed redundant declarations in Socket function.

I run tests. All is ok but the commented line is wrong. I'm not good with coffee script. This is why I didn't corrected test file.

### CODE REVIEW

**Comment by NathanGRomano** [comment]
I am checking it out now

**Comment by NathanGRomano** [comment]
Does this solve an issue?

**Comment by NathanGRomano** [comment]
I resolved the issue with the test. I will merge this.

**Comment by smart--petea** [comment]
Our team work on a little auction system. We need some socket functionality delivered by socket.io. To access it we must write something like `sock.sock.`. Now (if commit will be ok) our code will be more readable. 

Thank you for your work.

**Pull request merged**
