### PR TITLE
issue #11

### PR DESCRIPTION
**Pull request by smart--petea**

### CODE REVIEW

**Comment by smart--petea** [comment]
I tested on our project. The problem was in `this` of `Socket` constructor.

The snippet

```
function Socket(sock) {
  this.__proto__ = sock;
  this.emit =  function() {
    ...
     sock.emit.apply(sock, slice.call(arguments))
   }
}
```

mean that all info is obtained from sock, but not from `this`.

I changed it to 

```
function Socket(sock) {
  this.__proto__ = sock;

  var self = this;
  this.emit =  function() {
    ...
     sock.emit.apply(self, slice.call(arguments))
   }
}
```

This is important too for sending events by rooms

```
sock.broadcast.to('my-room').emit('message', 'some data')
```

**Comment by NathanGRomano** [comment]
@smart--petea thanks!

**Comment by NathanGRomano** [comment]
your pull request can not be automatically merged, it needs updated.

**Comment by NathanGRomano** [comment]
this was merged thanks

**Pull request closed without merging**
